[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[context.production]
 
  publish = "public/"
  command = "gatsby build"
  environment = { GATSBY_MODE = "production", GATSBY_PHLOEM_ENDPOINT = "https://api.treetoplearning.org" }

[context.branch-deploy]
  
  publish = "public/"
  command = "gatsby build"
  environment = { GATSBY_MODE = "develop", GATSBY_PHLOEM_ENDPOINT = "https://api.treetoplearning.org" }

[context.deploy-preview]
  
  publish = "public/"
  command = "gatsby build"
  environment = { GATSBY_MODE = "preview", GATSBY_PHLOEM_ENDPOINT = "https://api.treetoplearning.org" }

[dev]
  command = "gatsby develop"
  environment = { GATSBY_PHLOEM_ENDPOINT = "https://10.0.1.26:8080" }
